@startuml
scale 700 width
'scale 550 height

Shift_Register -d-> Read_Command
Read_Command -u-> Shift_Register

state Shift_Register {

IDLE_SHIFT_REG          : CS = 0\ncount = 8\nRCLK = 0
SRCLK_FALLING_SHIFT_REG : SRCLK = 0\nif(shift_reg & 0x01)\n\tDIO = 1\nelse\n\tDIO = 0
SRCLK_RISING_SHIFT_REG  : SRCLK = 1\ncount--\nshift_reg = shift_reg>>1
RLCK_ENABLE_SHIFT_REG   : SRCLK = 0 \n DIGITS off\nRCLK = 1\n SET DIGIT\n (act_digit++)&0x03

[*] -r-> IDLE_SHIFT_REG

IDLE_SHIFT_REG -r-> SRCLK_FALLING_SHIFT_REG

SRCLK_FALLING_SHIFT_REG -r-> SRCLK_RISING_SHIFT_REG : \t

SRCLK_RISING_SHIFT_REG -r-> RLCK_ENABLE_SHIFT_REG : count == 0
SRCLK_RISING_SHIFT_REG -l-> SRCLK_FALLING_SHIFT_REG : count != 0

RLCK_ENABLE_SHIFT_REG -l-> IDLE_SHIFT_REG
}

state Read_Command {
}
@enduml
